# Generated by Django 3.1.2 on 2021-08-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210821_0331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edges',
            old_name='destination',
            new_name='target',
        ),
    ]
